/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */


 /* 效率与杂谈: [
    'home',
    {
      type: 'category',
      label: '一些软件部署',
      items: ['hugo部署',
              'docusaurus部署'
    ],
    },
  ],*/

  测试: [
    {
      type: 'category',
      label: '基础知识',
      link: {
        type: 'generated-index',
        //description: '',
        keywords: ['硬件与半导体', '硬件与半导体基础知识', '电阻', '电容', '电感', '磁珠', '二极管', '三极管', 'MOS', '运算放大器', '数字电路', '设计规范', '推挽开漏', '共模差模', '储存介质', '锂电池', '编码器'],
      },
      items: [
        '个人知识库搭建-Docusaurus',
      ],
    },

    {
      type: 'category',
      label: '嵌入式硬件',
      link: {
        type: 'generated-index',
        //description: ' ',
        //keywords: ['硬件与半导体', '协议', '通信协议', '逻辑电平', 'SPI', 'I2C', 'CAN', 'USB', ],
      },
      items: [
        
        //'X86平台的硬件测试',
      ],
    },
  ],
};

module.exports = sidebars;
